name = "ThreadedArrays"
uuid = "9c11b073-d24e-40a7-a526-c896c0b3583b"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"

[compat]
Folds = "0.2.8"
julia = "1.6"
